"""add state field to conversation

Revision ID: 86eb72c12a1b
Revises: c79822487ea0
Create Date: 2026-07-11 18:57:53.038171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86eb72c12a1b'
down_revision: Union[str, Sequence[str], None] = 'c79822487ea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Добавляем колонку state в conversations
    op.add_column('conversations', sa.Column('state', sa.JSON(), nullable=True, server_default=sa.text("'{\"step\": 0, \"data\": {}}'::json")))
    
    # НЕ трогаем conversation_id в этой миграции, чтобы не падало
    # op.alter_column('chat_messages', 'conversation_id', nullable=False)  # закомментировано


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'state')
    op.alter_column('chat_messages', 'conversation_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
